### PR TITLE
Add Java track

### PR DESCRIPTION
**Pull request by mthmulders**
* [X] Simulation
* [X] Traffic Control application
* [x] Fine Collection application
* [x] Vehicle Registration application
* [x] Documentation (readme and generic texts)
* [x] Assignment 1
* [x] Assignment 2
* [x] Assignment 3
* [x] Assignment 4
* [x] Assignment 5
* [x] Assignment 6
* [x] Assignment 7
* [x] Upgrade to latest Dapr for Java SDK
* [x] Decide how to deal with shared stuff (Dapr component definitions, infrastructure scripts, ...)
* [ ] Update [end state repository](https://github.com/mthmulders/dapr-traffic-control) to show the fully working Java solution

### CODE REVIEW

**Comment by TomCools** [comment]
### **NOTE: WORK IN PROGRES. WILL UPDATE THIS COMMENT WITH MORE AS I PROGRESS THROUGH THE LAB.**

I'm running through the Java Workshop now, will list all my remarks or "To Think Abouts" here. 

Using: 
- IntelliJ **Community** Edition
- Java version "16.0.1" 2021-04-20
- Java(TM) SE Runtime Environment (build 16.0.1+9-24)
- Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

Registered Issues:
- Issue in connection between FineCollection and Vehicle Info: https://github.com/mthmulders/dapr-workshop/pull/1

- [ ] Documentation: Mention requirement for Maven/JDK 16 is installed and JAVA_HOME is pointing to JDK 16. I had multiple JDKs installed, but JAVA_HOME was set to JDK15-Loom.
- [ ] The ".http" files are not supported in the Community Edition of Intellij. Should we add a postman collection or just add the curl commands in the readme?
- [ ] A1: 'Traffic-control.http' part mentions 'Click on Execute Request for **both** request', but the file contains 3 request and the screenshot of the log-output you expect also indicates you need to click all 3.

**Comment by mthmulders** [comment]
@TomCools, thanks a lot for this massive amount of valuable feedback! I've already merged both your pull requests (an additional thanks for those!) and applied some of your textual suggestions.

There's a few things I'd like to start a conversation about...

> Documentation: Mention requirement for Maven/JDK 16 [etc...]

For sure! I consider that part of the open tasks ("Documentation (readme and generic texts)").

> IntelliJ Community Edition has a lot of red errors [...]  dissapeared as soon as I renamed the folders to lowercase (ex. from FineCollectionService to fine-collection-service).

I'm really surprised by this. The "root" POM has the same casing. Even on Linux (case-sensitive file system!) it works flawlessly, so I'm surprised that it doesn't work on Windows (case-insensitive file system, if I'm not mistaken). Does it work _without_ renaming when you build using `mvn package`?

> The ".http" files are not supported in the Community Edition of Intellij. Should we add a postman collection or just add the curl commands in the readme?

I was planning to list Visual Studio Code as "required" tool. It supports **.http** files. I've used a commercial license for IntelliJ so I wasn't aware that the community edition does not support those files.

> Inconsistant terminology: The service is called "VehicleRegistration" but the property for the url

I'm afraid something is missing there...

> TEXT A2: When creating the DaprVehicleRegistrationClient, maybe also add the full class examples of the FineCollectionConfiguration & the DaprVehicleRegistrationClient classes?

I've largely followed the text from the .NET-track, which (in most cases) does not list full files. There will be a "final state" repository available as well, in case people get stuck. I'm afraid such listings would be hard to maintain as soon as we change even the tiniest detail in the exercises...

> TEXT A2-Step4: It appears we suddenly have Zipkin. instead of going directly to the URL, maybe first have a look at the Docker Containers that have been started when we initialized Dapr?

I think that is covered in the Dapr installation instructions. I felt like not repeating that over here.

> Inconsistancy and Warning: The pulling of the RabbitMQ docker container might take a long time at a conference if we do this workshop there. We are also using a different RabbitMQ container in the Slides (rabbitmq:3-alpine) than in the Infrastructure/start-rabbitmq.sh file (rabbitmq:3-management-alpine)

Oops, should've been the one without the management interface. I just used it locally for some troubleshooting, but it's definitely not necessary for the workshop. Hopefully that saves a few megabytes. Additionally, if I were to run this workshop at a conference, I would give some pre-workshop advice (such as installing Dapr, and pulling in the necessary Docker containers). That should fix it for most of the users, hopefully...

> A3-Step5: We went to Zipkin in the previous lab, why not show off the RabbitMQ user interface?

Because I was planning not to use that at all - see above :-).

> TEXT: in the infrastructure folder, we use the "management" version of rabbitmq, which includes the dashboard. Maybe mention you can go there and the default username/password?

See above :-)

**Comment by mthmulders** [comment]
I've fixed a few of your "smaller" improvements, @TomCools, but unfortunately I can't tick off the boxes in your comment:

>     * [ ]  TEXT: A1: 'Traffic-control.http' part mentions 'Click on Execute Request for **both** request', but the file contains 3 request and the screenshot of the log-output you expect also indicates you need to click all 3.
>     * [ ]  TEXT A2: _"in the same class, the vehicleRegistrationClient method declares a Spring Bean that provides an implementation of the VehicleRegistrationClient interface. To do so, it needs a RestTemplate bean."_ -> pretty sure it needs to be _**"To do so, it needs a DaprClient bean"**_
>     * [ ]  TEXT A7-Step3: You say: "add a new Method  'daprClient' to declare .." in FineCollectionConfiguration. However, that method already exists from a previous assignment. So it should probibily be "change the method"... but only if you actualyl need the serializer, else there is no change.

**Comment by mthmulders** [comment]
> My gRPC server wouldn't start on port 60002 because of access permissions. Maybe we should use a different range than 6XXXX for the GRPC? (Use non Ephemeral ports: https://en.wikipedia.org/wiki/Ephemeral_port)
> The ports I was able to use succesfully:
>       
>    * --app-id trafficcontrolservice --app-port 6000 --dapr-http-port 3600 --dapr-grpc-port 36000
>    * --app-id finecollectionservice --app-port 6001 --dapr-http-port 3601 --dapr-grpc-port 36001
>    * --app-id vehicleregistrationservice --app-port 6002 --dapr-http-port 3602 --dapr-grpc-port 36002

@EdwinVW, I've used the same ports as you did for the .NET track. Any thoughts on this? I assume you where able to run the .NET services on those ports?

**Comment by TomCools** [comment]
> > IntelliJ Community Edition has a lot of red errors [...]  dissapeared as soon as I renamed the folders to lowercase (ex. from FineCollectionService to fine-collection-service).
> 
> I'm really surprised by this. The "root" POM has the same casing. Even on Linux (case-sensitive file system!) it works flawlessly, so I'm surprised that it doesn't work on Windows (case-insensitive file system, if I'm not mistaken). Does it work _without_ renaming when you build using `mvn package`?

yes, works fine with Maven, seems like IntelliJ couldn't deal with it properly (case sensitive). However, we should be pretty strict on the usage of other IDEs if this is the case. 

So for me:
- Either update the files so they are all lowercase
- Explicitly mention there are issues with IntelliJ?

**Comment by EdwinVW** [comment]
@mthmulders I would use the RabbitMQ with the management plugin. Sometimes in the workshop I use the UI to show people what exchanges and queues are being created by Dapr and to show that messages are actually being transported by RMQ.

---

> I've used the same ports as you did for the .NET track. Any thoughts on this? I assume you where able to run the .NET services on those ports?

Yes, I was able to use these ports on Windows. There is an issue though on Windows that sometimes the ports are reserved by HyperV which is used for Docker Desktop (see [this issue](https://github.com/docker/for-win/issues/3171)).

We could change the ports though if necessary. I would suggest to use the same ports in both the .NET and Java workshop though.

---

FYI: after this PR is merged, I will upgrade the .NET code to .NET 6. This has some impact on code-level (lots of new C# constructs) and obviously also on some code-snippets and step-by-step instructions.

**Comment by mthmulders** [comment]
Just discussed with @EdwinVW that he will add a note about the port usage - it's a thing that may or may not occur on Windows, regardless of the port range that we would choose.

**Comment by mthmulders** [comment]
The scripts & docs now mention the RabbitMQ image that comes with the management UI (again).

I suggest @TomCools and I can look at the IntelliJ issue seperately. If worst comes to worst, it would only affect the `java/` folder and the Java guides.

I would say we're good to merge now!

One last question for @EdwinVW which does not block the merge as far as I'm concerned: would you like the final Java solution to be included in your [dapr-traffic-control](https://github.com/edwinvw/dapr-traffic-control) repo, or would you prefer me to host a "dapr-traffic-control-java"?

**Comment by EdwinVW** [comment]
I would create a separate repo for the Java version of dapr-traffic-control. The .NET repo is also referenced in the 'Dapr for .NET developers' book, so it would not be right to also put the Java version into that same repo.

**Pull request merged**
